### ISSUE TITLE
Formula not working.

### ISSUE THREAD

**Issue by peterfaulks** [seznam/pyoo#11]
Firstly, thanks for a great project. It certainly makes my life a lot easier.

I have a snippet of code from a project I'm working on that has me beat...
```
#! /usr/bin/python3.4

import os, time, pyoo

os.system("soffice --accept=\"socket,host=localhost,port=2002;urp;\" --norestore --nologo --nodefault")
time.sleep(2)
desktop = pyoo.Desktop('localhost', 2002)
doc = desktop.create_spreadsheet()

for i in range(1, 7):
    doc.sheets[0][i, 2].formula = "=ROUND((B{0}*10000),0) ".format(i+1,)
```

Leaves an Err:508 (Bracket missing)

=ROUND((B2*10000),0)
The formula is right, and if you edit and enter it accepts it just fine.

Any clues as to what's happening?

Cheers

**Comment by peterfaulks** [comment]
Dunno why half my post is in bold and I can't fix it...

**Comment by mila** [comment]
My guess is that the extra space at the end of the formula can cause the problem.

But this does not look like a problem in PyOO so I'm closing this issue.

**Comment by peterfaulks** [comment]
Sorry, it doesn't work without the space either, I'd put that there as an attempt to see if it made a difference (which of course it doesn't), and forgot to remove it.

Edit:

It seems any function with a comma in it is failing
