### ISSUE TITLE
in python 2.7.9 don't work

### ISSUE THREAD

**Issue by ibmsdave** [seznam/pyoo#4]
apparently changed package uno:
```python
>>> import pyoo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyoo.py", line 26, in <module>
    FORMAT_TEXT = uno.getConstantByName('com.sun.star.i18n.NumberFormatIndex.TEXT')
AttributeError: 'module' object has no attribute 'getConstantByName'
```

or what am I doing wrong ?

**Comment by LavinJ** [comment]
Same issue here, on a virtualenv

```python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyoo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nt_3/workspace/bridgestone/env/local/lib/python2.7/site-packages/pyoo.py", line 26, in <module>
    FORMAT_TEXT = uno.getConstantByName('com.sun.star.i18n.NumberFormatIndex.TEXT')
AttributeError: 'module' object has no attribute 'getConstantByName'
```

I'm trying to find an older version of uno whos api supports `getConstantByName` method

**Comment by mila** [comment]
LavinJ is right. I am afraid that uno module is not available on PyPi.  We install uno from Debian package. It also is sometimes installed with LibreOffice. 

If you have LibreOffice / uno installed globally create virtualenv with `--system-site-packages` option.

Try example from http://www.openoffice.org/udk/python/python-bridge.html If you also get `AttributeError` then the problem is not in `pyoo` library. 

    import uno
    uno.getComponentContext

**Comment by VarunChawla** [comment]
Anybody got solution for this....

**Comment by mazzystr** [comment]
Still no solution?

**Comment by mcrapet** [comment]
On debian, `python-uno` seems to conflict with `python3-uno`. So I used:
```
$ pip3 install pyoo
```

**Comment by oginga** [comment]
After digging,I came across this statement  ```The only dependency is the Python-UNO library (imported as a module uno). Unfortunately Python-UNO cannot be installed using pip. Do NOT install package named uno available on PyPI - it’s not related to LibreOffice.``` on their site [https://pypi.org/project/pyoo/]
So uninstall all unofficial ```uno``` packages ```pip3 uninstall uno``` and run your script.
This worked despite not having any ```uno```  package on my ```pip3 freeze``` list and I had to enable site-packages on my virtualenv.
